let listeTaches = [
    {
        id: 1,
        titre: "Faire les courses",
        description: "Acheter du pain, du lait et des oeufs",
        date: "2021-01-01",
        statut: true,
    },
    {
        id: 2,
        titre: "Faire du sport",
        description: "Faire 30 minutes de sport",
        date: "2021-01-02",
        statut: false,
    },
    {
        id: 3,
        titre: "Lire un livre",
        description: "Lire 20 pages du livre 'Le seigneur des anneaux'",
        date: "2021-01-03",
        statut: false,
    },
    {
        id: 4,
        titre: "Apprendre à coder",
        description: "Apprendre à coder en JavaScript",
        date: "2021-01-04",
        statut: true,
    },
    {
        id: 5,
        titre: "Faire la vaisselle",
        description: "Faire la vaisselle",
        date: "2021-01-05",
        statut: false,
    },
    {
        id: 6,
        titre: "Faire le ménage",
        description: "Faire le ménage",
        date: "2021-01-06",
        statut: false,
    },
    {
        id: 7,
        titre: "Faire du jardinage",
        description: "Faire du jardinage",
        date: "2021-01-07",
        statut: true,
    },
    {
        id: 8,
        titre: "Faire du bricolage",
        description: "Faire du bricolage",
        date: "2021-01-08",
        statut: false,
    },
    {
        id: 9,
        titre: "Faire du yoga",
        description: "Faire 30 minutes de yoga",
        date: "2021-01-09",
        statut: false,
    },
    {
        id: 10,
        titre: "Faire une sieste",
        description: "Faire une sieste de 30 minutes",
        date: "2021-01-10",
        statut: false,
    },
];
export default listeTaches;
